parameters:
  - name: environment
    type: string
    values:
      - dev
      - hml
      - prd
  - name: dependsOn
    type: string
  - name: namespace
    type: string
  - name: appName
    type: string
  - name: subscription
    type: string
  - name: packageDirectory
    type: string

stages:
  - stage: ${{ parameters.environment }}
    displayName: ${{ parameters.environment }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: succeeded()

    jobs:
      - template: pipeline-templates/deploy-iac.yml@templates
        parameters:
          environment: ${{ parameters.environment }}
          terraformFilesPath: $(Build.SourcesDirectory)/.iac

      - job: Deployment
        dependsOn: IaC
        displayName: Release ${{ parameters.environment }}
        steps:
          - download: current
            displayName: "Download build artifacts"
            artifact: drop

          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: AzureRM
              azureSubscription: ${{ parameters.subscription }}
              appType: "webAppLinux"
              DeploymentType: zipDeploy
              WebAppName: ${{ parameters.namespace }}-${{ parameters.appName }}-${{ parameters.environment }}
              packageForLinux: ${{ parameters.packageDirectory }}
