trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnectionId: 'cd6de276-3a5b-458d-8edf-ea0907e684ca'
  webAppName: 'tpf-processingmodel'
  pythonVersion: '3.9'
  buildDirectory: '$(Build.ArtifactStagingDirectory)/build'
  outputZipDir: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
  downloadedPackageDirectory: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip

stages:
  - stage: "build"
    displayName: "Build"
    jobs:
      - job: "build"
        displayName: "Build"
        pool:
          name: Azure.Pool.Stronzo
      
        steps:
          - task: UsePythonVersion@0
            name: pyVersion
            inputs:
              versionSpec: $(pythonVersion)
              addToPath: true
              architecture: "x64"

          - task: Cache@2
            inputs:
              key: 'ai-model'
              path: '$(System.ArtifactsDirectory)/model'
              cacheHitVar: 'hasAiModel'

          - task: DownloadPackage@1
            condition: not(eq(variables.hasAiModel, 'true'))
            inputs:
              packageType: 'upack'
              feed: '/e1ea829c-6ca3-4442-9e79-b9d06a6782f7'
              view: 
              definition: '7ea22459-192d-42c0-8f4b-5f1c26a7a9cf'
              version: '1.0.1'
              downloadPath: $(System.ArtifactsDirectory)/model

          - task: CopyFiles@2
            displayName: Copy keras model
            inputs:
              SourceFolder: "$(System.ArtifactsDirectory)/model"
              Contents: "*.tflite"
              TargetFolder: $(buildDirectory)
              CleanTargetFolder: true

          - task: CopyFiles@2
            displayName: Copy api files
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)/src"
              Contents: "**"
              TargetFolder: $(buildDirectory)
              CleanTargetFolder: false

          - script: |
              python -m venv .venv
              source .venv/bin/activate
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            workingDirectory: $(buildDirectory)
            displayName: "Install requirements"

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: $(buildDirectory)
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(outputZipDir)
              replaceExistingArchive: true
              
          - publish: $(outputZipDir)
            displayName: 'Publish artifact'
            artifact: drop

  - stage: deploy
    displayName: 'Deploy Web App'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - job: Deploy
        pool:
          name: Azure.Pool.Stronzo
        steps:
          - task: UsePythonVersion@0
            name: pyVersion
            inputs:
              versionSpec: $(pythonVersion)
              addToPath: true
              architecture: "x64"

          # Downloads to $(Pipeline.Workspace)/current
          - download: current
            artifact: drop
            displayName: "Download build artifacts"
          
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: AzureRM
              azureSubscription: 'Azure para Estudantes (26956325-be9b-439d-b44f-c8a6540154e2)'
              appType: 'webAppLinux'
              DeploymentType: zipDeploy
              WebAppName: 'stronzo-tapegandofogo-processingmodel-dev'
              packageForLinux: '$(downloadedPackageDirectory)'
