trigger:
  branches:
    include:
      - main

variables:
  azureServiceConnectionId: 'cd6de276-3a5b-458d-8edf-ea0907e684ca'
  webAppName: 'tpf-processingmodel'
  environmentName: 'tpf-processingmodel'

  pythonVersion: '3.10'
  buildDirectory: '$(Build.ArtifactStagingDirectory)/build'
  outputZipDir: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip

stages:
  - stage: "build"
    displayName: "Build"
    jobs:
      - job: "build"
        displayName: "Build"
        pool:
          name: Azure.Pool.Stronzo
      
        steps:
          - task: UsePythonVersion@0
            name: pyVersion
            inputs:
              versionSpec: $(pythonVersion)
              addToPath: true
              architecture: "x64"

          - task: DownloadPackage@1
            inputs:
              packageType: 'upack'
              feed: '/e1ea829c-6ca3-4442-9e79-b9d06a6782f7'
              view: 
              definition: '7ea22459-192d-42c0-8f4b-5f1c26a7a9cf'
              version: '1.0.0'
              downloadPath: $(System.ArtifactsDirectory)

          - task: CopyFiles@2
            displayName: Copy keras model
            inputs:
              SourceFolder: "$(System.ArtifactsDirectory)"
              Contents: "*.h5"
              TargetFolder: $(buildDirectory)
              CleanTargetFolder: false

          - task: CopyFiles@2
            displayName: Copy api files
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)/src"
              Contents: "**"
              TargetFolder: $(buildDirectory)
              CleanTargetFolder: false

          - script: |
              python -m venv .venv
              source .venv/bin/activate
              python -m pip install --upgrade pip
              pip install -r requirements.txt
            workingDirectory: $(buildDirectory)
            displayName: "Install requirements"

          - task: ArchiveFiles@2
            displayName: 'Archive files'
            inputs:
              rootFolderOrFile: $(buildDirectory)
              includeRootFolder: false
              archiveType: zip
              archiveFile: $(outputZipDir)
              replaceExistingArchive: true

          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App : tpf-processingmodel'
            inputs:
              appType: webAppLinux
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: $(outputZipDir)
