trigger:
  branches:
    include:
      - main

stages:
  - stage: "build"
    displayName: "Build"
    jobs:
      - job: "build"
        displayName: "Build"
        pool:
          name: Azure.Pool.Stronzo
      
        steps:
          - task: CopyFiles@2
            displayName: Copy api files
            inputs:
              SourceFolder: "$(Build.SourcesDirectory)"
              Contents: "api.py"
              TargetFolder: "$(Build.ArtifactStagingDirectory)/build"
              CleanTargetFolder: true
            
          - task: PublishBuildArtifacts@1
            displayName: Publish
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)/build"
              ArtifactName: "$(Build.Repository.Name)-$(Build.BuildNumber)"
              publishLocation: "Container"
